[API]
name=OH7RDA
what=loc
apikey=TA_CLE_API_ICI
format=json
; Fréquence de mise à jour en millisecondes (ex: 60000 pour 1 minute)
interval=60000 

[Database]
host=172.18.58.85
username=root
password=toto
database=nom_de_ta_base

[WebSocket]
port=12345
