[API]
name="F4GOH-10,F4IKQ-9"
what=loc
whatwx=wx
apikey=
format=json
; Fréquence de mise à jour en millisecondes (ex: 60000 pour 1 minute)
interval=60000 

[Database]
host=
username=
password=
database=ballon2026

[WebSocket]
port=12345
