[API]
name="F4KMN-8,F4KMN-10"
what=loc
what_wx=wx
apikey=223953.dal2YpEozQQEiD
format=json
; Fréquence de mise à jour en millisecondes (ex: 60000 pour 1 minute)
interval=60000

[Database]
host=172.18.58.85
username=root
password=toto
database=ballon2026

[WebSocket]
port=12345
